### ISSUE TITLE
Actividad 7 Diagrama de clases modelo blockchain

### ISSUE THREAD

**Issue by JudithReynaCS** [SistemasTecTlaxiaco/actividad-7-diagrama-de-clases-modelo-blockchain-equipo-judith#1]
[Práctica Núm. 7.-Diagrama de clases modelo blockchain.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-diagrama-de-clases-modelo-blockchain-equipo-judith/files/11594044/Practica.Num.7.-Diagrama.de.clases.modelo.blockchain.pdf)

**Comment by Gregorio012** [comment]
Calificación 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
